### ISSUE TITLE
Reusing an open connection

### ISSUE THREAD

**Issue by teehamaral** [jlguardi/yowsup#48] opened 2016-04-05 13:09 UTC
Hello guys. How could I solve the reconnection problem by reusing an already open, for example, use the same send connection to listen on different instances and environments (could be using the connection HEX)? Someone is using this solution or could help me implement it?

**Comment by freelo** [comment] 2016-04-05 14:30
Would you be so kind and restrict your issue to one repository? Thanks. (Exact duplicate of tgalal/yowsup #1459)

**Comment by jlguardi** [comment] 2016-04-05 14:36
Duplicated.

**Closed as completed by jlguardi** 2016-04-05 14:36 UTC
