### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by rump1992** [jlguardi/yowsup#5] opened 2016-03-28 00:08 UTC
Hey,

thanks for the great work!

got this problem:

Auth: Logged in!
[connected]:[#############@s.whatsapp.net(28-03-2016 02:05)]:[1DA39D60DB936A865B9CB253E6B86C]     ###################
Message 1DA39D60DB936A865B9CB253E6B86C: Sent delivered receipt and Read
[connected]:
Traceback (most recent call last):
  File "yowsup-cli", line 323, in <module>
    if not parser.process():
  File "yowsup-cli", line 227, in process
    self.startCmdline()
  File "yowsup-cli", line 255, in startCmdline
    stack.start()
  File "C:\Users\Dennis Rump\yowsup\yowsup\demos\cli\stack.py", line 25, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "C:\Users\Dennis Rump\yowsup\yowsup\stacks\yowstack.py", line 187, in loop
    asyncore.loop(_args, *_kwargs)
  File "C:\Users\Dennis Rump\AppData\Local\Programs\Python\Python35-32\lib\asyncore.py", line 203, in loop
    poll_fun(timeout, map)
  File "C:\Users\Dennis Rump\AppData\Local\Programs\Python\Python35-32\lib\asyncore.py", line 150, in poll
    read(obj)
  File "C:\Users\Dennis Rump\AppData\Local\Programs\Python\Python35-32\lib\asyncore.py", line 87, in read
    obj.handle_error()
  File "C:\Users\Dennis Rump\AppData\Local\Programs\Python\Python35-32\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "C:\Users\Dennis Rump\AppData\Local\Programs\Python\Python35-32\lib\asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "C:\Users\Dennis Rump\yowsup\yowsup\layers\network\layer.py", line 86, in handle_read
    self.receive(data)
  File "C:\Users\Dennis Rump\yowsup\yowsup\layers\network\layer.py", line 94, in receive
    self.toUpper(data)
  File "C:\Users\Dennis Rump\yowsup\yowsup\layers__init__.py", line 59, in toUpper
    self.**upper.receive(data)
  File "C:\Users\Dennis Rump\yowsup\yowsup\layers\stanzaregulator\layer.py", line 28, in receive
    self.processReceived()
  File "C:\Users\Dennis Rump\yowsup\yowsup\layers\stanzaregulator\layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "C:\Users\Dennis Rump\yowsup\yowsup\layers__init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "C:\Users\Dennis Rump\yowsup\yowsup\layers\auth\layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "C:\Users\Dennis Rump\yowsup\yowsup\layers__init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "C:\Users\Dennis Rump\yowsup\yowsup\layers\coder\layer.py", line 35, in receive
    self.toUpper(node)
  File "C:\Users\Dennis Rump\yowsup\yowsup\layers__init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "C:\Users\Dennis Rump\yowsup\yowsup\layers\logger\layer.py", line 14, in receive
    self.toUpper(data)
  File "C:\Users\Dennis Rump\yowsup\yowsup\layers__init**.py", line 59, in toUpper
    self.__upper.receive(data)
  File "C:\Users\Dennis Rump\yowsup\yowsup\layers\axolotl\layer.py", line 118, in receive
    self.onMessage(protocolTreeNode)
  File "C:\Users\Dennis Rump\yowsup\yowsup\layers\axolotl\layer.py", line 140, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "C:\Users\Dennis Rump\yowsup\yowsup\layers\axolotl\layer.py", line 225, in handleEncMessage
    self.handleWhisperMessage(node)
  File "C:\Users\Dennis Rump\yowsup\yowsup\layers\axolotl\layer.py", line 275, in handleWhisperMessage
    plaintext = sessionCipher.decryptMsg(whisperMessage)
  File "C:\Users\Dennis Rump\AppData\Local\Programs\Python\Python35-32\lib\site-packages\axolotl\sessioncipher.py", line 83, in decryptMsg
    return plaintext.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 1: invalid start byte

**Comment by rump1992** [comment] 2016-03-28 00:17
Looks like it's not possible to make break spaces in message neither

**Comment by jlguardi** [comment] 2016-03-28 03:11
Try with develop branch. I couldn't reproduce this error.

**Comment by jlguardi** [comment] 2016-03-30 12:44
I'll clos due to no more reports and probably fixed with last commits.

**Closed as completed by jlguardi** 2016-03-30 12:44 UTC
